### ISSUE TITLE
Grouped flag doesn't seem to work right around new TOML syntax

### ISSUE THREAD

**Issue by jplatte** [DevinR528/cargo-sort#104]
Using `.workspace = true` seems to confuse `cargo-sort` some of the time. This example should not get reformatted with `cargo sort --grouped`, but it does:

```toml
[package]
name = "cargo-sort-test"
version = "0.1.0"
edition = "2021"

[dependencies]
doesnotexistb.workspace = true

doesnotexista.workspace = true
```

cc @thomaseizinger
