### ISSUE TITLE
`cargo-sort` 2.0.1 reorders more than just dependencies

### ISSUE THREAD

**Issue by smoelius** [DevinR528/cargo-sort#106]
Following a recent upgrade to version 2.0.1, `cargo sort --grouped` wants to move [several sections](https://github.com/trailofbits/dylint/blob/6db435a98a7045fe64ce44a4c7901f56016c8c81/examples/testing/clippy/Cargo.toml#L36-L47) to just below the `[package]` section near the top of a Cargo.toml file.

Specifically, `cargo sort --grouped` seems to prefer the following over [what's there now](https://github.com/trailofbits/dylint/blob/6db435a98a7045fe64ce44a4c7901f56016c8c81/examples/testing/clippy/Cargo.toml#L1-L10):
```toml
[package]
name = "clippy"
version = "4.1.0"
authors = ["Samuel E. Moelius III <sam@moeli.us>"]
description = "All of the Clippy lints as a Dylint library"
edition = "2024"
publish = false

[package.metadata.rust-analyzer]
rustc_private = true

[workspace]

[workspace.metadata.dylint]
libraries = [
    { path = "../../general" },
    { path = "../../supplementary" },
    { path = "../../testing/clippy" },
    { path = "../../restriction/*" },
]

[lib]
crate-type = ["cdylib"]
```
This behavior is surprising to me because (I believe) `cargo-sort` used to reorder just dependencies.
