### ISSUE TITLE
Feature request: normalize tables

### ISSUE THREAD

**Issue by ModProg** [DevinR528/cargo-sort#37]
I'd like an option, turning inline tables into normal tables, and vice versa.

So from
```toml
[dependencies]
serde = {version = "1", features = ["derive"]}

[dependencies.log]
version = "0.4"
features = ["std"]
```
to

```toml
[dependencies]
serde = {version = "1", features = ["derive"]}
log = { version = "0.4", features = ["std"]}
```
or 
```toml
[dependencies.serde]
version = "1" 
features = ["derive"]

[dependencies.log]
version = "0.4"
features = ["std"]
```
Depending on the flag / config given.
