### ISSUE TITLE
Cargo.toml without trailing newlines is not considered sorted

### ISSUE THREAD

**Issue by DesmondWillowbrook** [DevinR528/cargo-sort#43]
```toml
[package]
name = "placeholder-name"
version = "0.1.0"
edition = "2021"
[dependencies]
axum = { path = "../../axum" }
hyper = { version = "0.14", features = ["full"] }
tokio = { version = "1", features = ["full"] }
```

is _not_ considered sorted when running `cargo sort --workspace --grouped --check`, while the same snipped with a trailing newline _is_.

### Version
Run with `cargo-sort v1.0.7`
